app_config:
  zoom_factor: 2.0
  selection_grid_size:  [2, 1]
  selection_image_height_py: 700
  frame_padx: 10
  frame_pady: 10

input_prompt_image_height: 1080
debug_inputs: False
sort_based_on: "highest_score"
max_size_to_add: 40
save_image_and_masks: False
