app_config:
  visualize_input_prompt: True
  selection_grid_size:  [2, 1]
  selection_image_height_px: 700
  frame_padx: 10
  frame_pady: 10

save_root_path: "data/ctr_capture_apr_25_24"
debug_inputs: False
apply_mask: True
test_num: 2 # Set to -1, for all
sort_based_on: "highest_score"

# SAM Predictor
# batch_size: 1000 # Data loading into memory, and inference

